language: swift
osx_image: xcode9.3beta
script: xcodebuild -workspace DataDog.xcworkspace -scheme DataDog -sdk iphonesimulator11.3 -destination 'platform=iOS Simulator,OS=11.3,name=iPhone 8' -configuration Debug build
